spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_app_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  messages:
    encoding: "UTF-8"
    basename: "i18n/messages" # directory with messages_XX.properties
    use-code-as-default-message: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      temp:
        use_jdbc_metadata_defaults: false